---
all:
  children:

    nfs_servers:
      hosts:
        shack-fil-p001:
        shack-fil-p002:

    nfs_clients:
      hosts:
        shack-app-p001:
        shack-app-p002:
        shack-app-p003:
