---
- name: Install NFS client
  ansible.builtin.apt:
    name: "{{ nfs_client_package }}"
    state: present
    update_cache: true
  become: true

- name: Create NFS mount directories
  ansible.builtin.file:
    path: "{{ item.mountpoint }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
  loop: "{{ nfs_mounts }}"
  become: true

- name: Configure NFS mounts
  ansible.posix.mount:
    path: "{{ item.mountpoint }}"
    src: "{{ item.server }}:{{ item.export }}"
    fstype: "{{ item.fstype | default(nfs_mount_defaults.fstype) }}"
    opts: "{{ item.options | default(nfs_mount_defaults.options) | join(',') }}"
    state: present
  loop: "{{ nfs_mounts }}"
  become: true

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true
